# Generated by Django 5.0.4 on 2024-04-13 08:20

import django.db.models.deletion
import service.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Palette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Палитры',
                'verbose_name_plural': 'Палитры',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex_color', models.CharField(max_length=7, validators=[service.validators.ColorHexValidator()], verbose_name='HEX цвета')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Название')),
                ('palette', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.palette', verbose_name='Идентификатор палитры')),
            ],
            options={
                'verbose_name': 'Цвета',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.AddConstraint(
            model_name='palette',
            constraint=models.UniqueConstraint(fields=('user', 'title'), name='unique_palette_with_user'),
        ),
        migrations.AddConstraint(
            model_name='color',
            constraint=models.UniqueConstraint(fields=('palette', 'hex_color'), name='unique_palette_with_hex_color'),
        ),
        migrations.AddConstraint(
            model_name='color',
            constraint=models.UniqueConstraint(fields=('palette', 'title'), name='unique_palette_with_title'),
        ),
    ]
