# Generated by Django 5.0.4 on 2024-04-14 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='palette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.palette', verbose_name='Идентификатор палитры'),
        ),
    ]
