# Generated by Django 5.0.4 on 2024-04-14 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_color_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='palette',
            name='unique_palette_with_user',
        ),
        migrations.AddConstraint(
            model_name='palette',
            constraint=models.UniqueConstraint(fields=('user', 'title'), name='unique_palette_with_user', violation_error_message='У этого пользователя уже есть палитра с таким названием'),
        ),
    ]
