# Generated by Django 5.0.4 on 2024-04-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_remove_palette_unique_palette_with_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='color',
            name='unique_palette_with_hex_color',
        ),
        migrations.RemoveConstraint(
            model_name='color',
            name='unique_palette_with_title',
        ),
        migrations.AddConstraint(
            model_name='color',
            constraint=models.UniqueConstraint(fields=('palette', 'hex_color'), name='unique_palette_with_hex_color', violation_error_message='В одной палитре не может быть двух одинаковых цветов'),
        ),
        migrations.AddConstraint(
            model_name='color',
            constraint=models.UniqueConstraint(fields=('palette', 'title'), name='unique_palette_with_title', violation_error_message='В одной палитре не может быть двух одинаковых цветов'),
        ),
    ]
